name: markd
version: 0.5.0+1
authors:
- Dart Team <misc@dartlang.org>
- Tom Yeh <tomyeh@rikulo.org>
description: A fork of dart-markdown for converting markdown to HTML.
homepage: https://github.com/tomyeh/markd
dev_dependencies:
  unittest: any
