name: markd
version: 0.5.1
authors:
- Dart Team <misc@dartlang.org>
- Tom Yeh <tomyeh@rikulo.org>
description: A fork of dart-markdown for easy customizing markdown syntaxes.
homepage: https://github.com/tomyeh/markd
dev_dependencies:
  unittest: any
